name: Java CI with Gradle

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]

# Список "работ" или заданий, которые будут выполняться
jobs:
  # Название работы - "build-and-test"
  build-and-test:
    # Запускать на последней версии Ubuntu
    runs-on: windows-latest

    # Стратегия "матрицы" для запуска на нескольких версиях Java
    strategy:
      # Не останавливать все сборки, если одна из них упала
      fail-fast: false
      matrix:
        java: [ 11, 17, 21 ]

    # Шаги, которые будут выполнены для каждой версии Java из матрицы
    steps:
      # 1. Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Установка нужной версии JDK
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      # 3. Создание файла конфигурации app.properties
      # Этот шаг будет выполнен перед сборкой. Он создает нужные директории и файлы.
      #- name: Create app.properties file
       # run: |
        #  mkdir -p src/main/resources
         # echo "urls.file.path=urls.txt" > src/main/resources/app.properties
          #echo "http.timeout.ms=5000" >> src/main/resources/app.properties
          #echo "http.method=HEAD" >> src/main/resources/app.properties
          
          # Копируем созданный файл и для тестов
          #mkdir -p src/test/resources
          #cp src/main/resources/app.properties src/test/resources/app.properties
          
          # Также создаем файл urls.txt, так как он тоже может быть в .gitignore
          #echo "https://google.com" > src/main/resources/urls.txt
          #echo "https://github.com" >> src/main/resources/urls.txt
          #cp src/main/resources/urls.txt src/test/resources/urls.txt


      # 4. Предоставление прав на выполнение для Gradle Wrapper
     # - name: Grant execute permission for gradlew
     #   run: chmod +x gradlew

      # 5. Запуск статического анализа Checkstyle
      # - name: Run Checkstyle
       # run: gradlew.bat checkstyleMain

      # 6. Сборка проекта и запуск тестов
      - name: Build with Gradle
        run: gradlew.bat build
      - name: JavaVersion
        run: java --version
