name: Java CI with Gradle

# Триггер: запускать рабочий процесс при push в любую ветку
on: [push]

# Список "работ" или заданий, которые будут выполняться
jobs:
  # Название работы - "build-and-test"
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      # Не останавливать все сборки, если одна из них упала
      fail-fast: false
      matrix:
        # список версий Java, на которых нужно запустить сборку
        java: [ 11, 17, 21 ]

    steps:
      # 1. Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Установка нужной версии JDK
      # action 'setup-java' для установки Java
      # Версия Java будет подставлена из матрицы (11, 17 или 21)
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      # 3. Предоставление прав на выполнение для Gradle Wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Запуск статического анализа Checkstyle
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

      # 5. Сборка проекта и запуск тестов
      - name: Build with Gradle
        run: ./gradlew build